### ISSUE TITLE
xlim and ylim arguments in euplot() are not the ggplot limits

### ISSUE THREAD

**Issue by konradmayer** [cszang/regmap#1]
_this time in English in case a non-German speaker stops by:_

The xlim and ylim function arguments of the function are not in the ggplot statement (https://github.com/cszang/eumap/blob/6a2bcea5ee03e2e637bab45984799d9e203e98f3/R/eumap.R#L26). Is that intended? I would expect the function to behave like this:

``` r
  ggplot(data = .data,
         aes_string(x = .lon, y = .lat)) +
    geom_polygon(data = world, aes(x = X,  y = Y, group = PID),
                 colour = "#BBBBBB", fill = "#DDDDDD") +
    theme_minimal() +
    xlim(xlim) + ylim(ylim) +
    xlab("Longitude") + ylab("Latitude") +
    coord_quickmap()
```

by the way - I love that you share your little helper packages - and that I get the notifications of new ones now I'm your collaborator on github. I should start to do that too...

**Comment by cszang** [comment]
Thanks for spotting! Fixed now, and I also made the colour/fill setting for the EU map function arguments.
Ah, I did not know you would be automatically notified, seems convenient. And, yes, I think putting convencience stuff in the public encourages packaging stuff (and having some kind of documentation as side effect).
