### ISSUE TITLE
regmap not available for R version 3.6.0

### ISSUE THREAD

**Issue by antonycastro** [cszang/regmap#3]
Hello,

I updated to R version 3.6.0 and since then I can´t use the "regmap" package. Could you update the package to version 3.6.0, please?

> install.packages("regmap")
Installing package into ‘C:/Users/Tony/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘regmap’ is not available (for R version 3.6.0)

Best regards,

**Comment by cszang** [comment]
Hi!

regmap is not on CRAN. Try

devtools::install_github(„cszang/regmap“)

Make sure the quotes are correct strings (not doable on iPhone).

Cheers, Christian

**Comment by antonycastro** [comment]
Done. It worked smoothly! Thanks for the explanation

Kind regards,
Tony
